### PR TITLE
repaircodelikeanddislike

### PR DESCRIPTION
**Pull request by rajafathurrahman**

### CODE REVIEW

**Comment by rajafathurrahman** [comment]
base on your country, change 'suka' as like and 'tidak suka' as 'dislike'

**Comment by hridaydutta123** [comment]
Thanks for the commit @rajafathurrahman. Can you please generalize it so that it works for any country? Or if you want to use 'suka' and 'tidak suka', can you please send 'country' as a parameter so that it is understandable to the general audience.

**Comment by rajafathurrahman** [comment]
thanks for comment. OK I try to generalize the code

**Comment by rajafathurrahman** [comment]
@hridaydutta123 I have to generalize the code, so this code can grab youtube like count and dislike count

**Comment by hridaydutta123** [comment]
Thanks for the PR! It is merged now.

**Pull request merged**
